services:

  db:
    image: mariadb
    restart: always
    volumes:
      - "dbdata:/var/lib/mysql"
    env_file: ".env"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}

  phpfpm:
    image: bitnami/php-fpm
    volumes:
      - "./:/app"
    depends_on:
      - db  

  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/prod.conf:/etc/nginx/nginx.conf"
      - "./:/app"
    ports:
      - 80:80
    depends_on:
      - phpfpm

volumes:
  dbdata:
    driver: local