name: Monsq CI/CD

on:
    push:
        branches: ['main']
          
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v1.1.0
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                script: |
                    cd inscreation.fr
                    git pull origin main
                    docker compose -f compose-prod.yml down
                    docker compose -f compose-prod.yml up -d
